[env]
HELM_PLUGINS = ".helm-plugins"

[settings]
experimental = true

[tools]
go = "latest"
"go:sigs.k8s.io/kind" = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"
kubie = "latest"

[tools.helmfile]
version = "latest"
postinstall = "mise x -- helmfile init --force"
