[env]
HELM_PLUGINS = ".helm-plugins"

[settings]
experimental = true

[tools]
"kind" = "latest"
helm = "latest"
kubectl = "latest"

[tools.helmfile]
version = "latest"
postinstall = "mise x -- helmfile init --force"
